services:
  postgres:
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "guest"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "my-db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
